[package]
name = "gkvocab_test"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde-xml-rs = "0.8.1"
xml-rs = "0.8.27"
uuid = { version = "1.18.0", features = ["v4", "v7", "serde"] }
regex = "1.11.2"
